#查看springboot开启了哪些配置
debug: false
mybatis:
  mapper-locations: classpath:mappings/*.xml  # 注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.integrated.shiros.model  # 注意：对应实体类的路径
  configuration:
    use-generated-keys: false # 使用jdbc的getGeneratedKey获取数据库自增主键 因为用uuid 作为主键 所以设置为false
    use-column-label: true # 使用标签替换列别名 默认是true
    map-underscore-to-camel-case: true # 使用驼峰命名转换：Table{create_time} --> entity{createTime}
#    auto-mapping-behavior: partial
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
urlfilter:
  startwith:
    demo: demo
  endwith:
    html: .html
    css: .css
    js: .js
    jpg: .jpg
    ico: .ico
  completely:
    login: login

spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
  thymeleaf:
    prefix: classpath:/pages/
    cache: false
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**