server:
  port: 23400
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://127.0.0.1/integrated?useSSL:FALSE&serverTimezone:UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: log4j,wall,mergeStat  #    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connectionProperties: druid.stat.mergeSql:true
    db-name: integrated
  redis:
    host: 127.0.0.1
    post: 6379
    timeout: 20000
#    cluster:
#      nodes: 127.0.0.1
#      max-redirects: 6
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1