server:
  port: 21200

##########################################################
##################  所有profile共有的配置  #################
##########################################################


##################  spring配置  ###################
#    dfs:
#      readUrl: https://www.xinlianpu.com:9999
#  freemarker:
#    suffix: .html
#    viewClass: org.springframework.web.servlet.view.freemarker.FreeMarkerView
#    content-type: text/html;charset=UTF-8
#    template-loader-path: classpath:/webapp/pages/
#    settings:
#      number_format: 0.##
#      template_update_delay: 0
#  devtools:
#    restart:
#      enabled: true




#  mvc:
#    static-path-pattern: /static/**
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/webapp/static/,classpath:/webapp/static/,classpath:/META-INF/resources/webapp/static/
#    static-locations: classpath:/webapp/static/
#  http:
#    converters:
#      preferred-json-mapper: fastjson
#    multipart:
#      max-request-size: 100MB #最大请求大小
#      max-file-size: 100MB #最大文件大小
#  devtools:
#    restart:
#      enabled: false #是否开启开发者工具（true/false）
#      additional-paths: src/main/java
#      exclude: static/**,pages/**
#  aop:
#    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理

---
##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://127.0.0.1/integrated?useSSL=FALSE&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    filters: stat
    filters: log4j,wall,mergeStat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connectionProperties: druid.stat.mergeSql=true
    db-name: integrated
  thymeleaf:
    prefix: classpath:/pages/
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mappings/*.xml  # 注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.integrated.shiros.model  # 注意：对应实体类的路径
  configuration:
    use-generated-keys: false # 使用jdbc的getGeneratedKey获取数据库自增主键 因为用uuid 作为主键 所以设置为false
    use-column-label: true # 使用标签替换列别名 默认是true
    map-underscore-to-camel-case: true # 使用驼峰命名转换：Table{create_time} --> entity{createTime}
    auto-mapping-behavior: partial


##########################################################
###################  dubbo 配置 ###################
##########################################################
#dubbo:
#  application:
#    name: village-dubbo-consumer
   # protocol:
    # name: dubbo
    # host: 127.0.0.1
    # port: 20880
#  registry:
#    protocol: zookeeper
#    address: 127.0.0.1
#    port: 2181
#logging:
#  level.root: info
#  level.com.stylefeng: debug
#  path: logs/
#  file: guns.log
#
